### ISSUE TITLE
Beautify timeline

### ISSUE THREAD

**Issue by peterschen** [tyayers/AzureResourceDiff#8]
The timeline currently shows an excerpt of changes to resource provides but do not show all the details. I think it might make sense to limit the timeline overview to just the amount of changes comparable to a git commit (e.g. lines deleted, lines added) and show the full diff when opening up more information.

**Comment by tyayers** [comment]
Agree, not enough time to rework as described, however have now collapsed the namespaces, can be expanded as needed + full diff available through button.  Looking forward to v2 to give a better summary of the changes in the overview 👍
